import { jsPDF } from 'jspdf';
import { format, parseISO } from 'date-fns';

export interface ReceiptData {
  payment: {
    id: string;
    amount_cents: number;
    expected_date: string;
    received_date: string | null;
    method: string | null;
    status: string;
    notes: string | null;
  };
  property: { address: string };
  landlord: { name: string | null; email: string };
  tenant: { name: string | null; email: string | null };
}

export function generateReceipt({
  payment,
  property,
  landlord,
  tenant,
}: ReceiptData): Uint8Array {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const left = 56;
  let y = 72;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('Rent Receipt', left, y);

  y += 14;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Receipt ID: ${payment.id}`, left, y);

  y += 30;
  doc.setTextColor(20);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Property', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text(property.address, left + 90, y);

  y += 18;
  doc.setFont('helvetica', 'bold');
  doc.text('Landlord', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `${landlord.name ?? landlord.email}${landlord.name ? ` (${landlord.email})` : ''}`,
    left + 90,
    y,
  );

  y += 18;
  doc.setFont('helvetica', 'bold');
  doc.text('Tenant', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text(tenant.name ?? tenant.email ?? '—', left + 90, y);

  y += 30;
  doc.setDrawColor(220);
  doc.line(left, y, 555, y);
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.text('Amount paid', left, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(20);
  doc.text(`$${(payment.amount_cents / 100).toFixed(2)}`, 555, y, { align: 'right' });

  y += 28;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Date received', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text(
    payment.received_date
      ? format(parseISO(payment.received_date), 'PPP')
      : 'Pending',
    555,
    y,
    { align: 'right' },
  );

  y += 18;
  doc.setFont('helvetica', 'bold');
  doc.text('For rent period including', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text(format(parseISO(payment.expected_date), 'PPP'), 555, y, { align: 'right' });

  y += 18;
  doc.setFont('helvetica', 'bold');
  doc.text('Method', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text((payment.method ?? '—').toUpperCase(), 555, y, { align: 'right' });

  y += 18;
  doc.setFont('helvetica', 'bold');
  doc.text('Status', left, y);
  doc.setFont('helvetica', 'normal');
  doc.text(payment.status, 555, y, { align: 'right' });

  if (payment.notes) {
    y += 30;
    doc.setFont('helvetica', 'bold');
    doc.text('Notes', left, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(payment.notes, 500);
    doc.text(lines, left, y);
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(160);
  doc.text(
    'Generated by It Rents · keep for your records.',
    left,
    750,
  );

  return doc.output('arraybuffer') as unknown as Uint8Array;
}
