'use server';

import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { addMonths, format, parseISO } from 'date-fns';
import { createClient } from '@/lib/supabase/server';

type ApplianceType = 'general' | 'hvac_filter' | 'sprinkler';

function nonEmpty(v: FormDataEntryValue | null): string | null {
  const s = (v as string | null)?.toString().trim();
  return s ? s : null;
}

function parseIntervalMonths(v: FormDataEntryValue | null): number | null {
  const s = (v as string | null)?.toString().trim();
  if (!s) return null;
  const n = Number(s);
  if (!Number.isFinite(n) || n < 1 || n > 120) return null;
  return Math.round(n);
}

function parseType(v: FormDataEntryValue | null): ApplianceType {
  const s = (v as string | null)?.toString();
  if (s === 'hvac_filter' || s === 'sprinkler') return s;
  return 'general';
}

export async function upsertAppliance(
  propertyId: string,
  applianceId: string | null,
  formData: FormData,
) {
  const supabase = createClient();

  const applianceType = parseType(formData.get('appliance_type'));
  const intervalMonths =
    applianceType === 'sprinkler'
      ? null
      : parseIntervalMonths(formData.get('service_interval_months'));
  const lastService =
    applianceType === 'sprinkler' ? null : nonEmpty(formData.get('last_service_date'));
  let nextServiceDue =
    applianceType === 'sprinkler' ? null : nonEmpty(formData.get('next_service_due'));

  // Auto-fill next service date when the user gave us an interval + last
  // service date but didn't supply next_service_due themselves.
  if (intervalMonths && lastService && !nextServiceDue) {
    nextServiceDue = format(
      addMonths(parseISO(lastService), intervalMonths),
      'yyyy-MM-dd',
    );
  }

  const payload = {
    property_id: propertyId,
    name: String(formData.get('name') ?? '').trim(),
    appliance_type: applianceType,
    install_date: nonEmpty(formData.get('install_date')),
    warranty_end: applianceType === 'general' ? nonEmpty(formData.get('warranty_end')) : null,
    serial: applianceType === 'general' ? nonEmpty(formData.get('serial')) : null,
    model: applianceType === 'general' ? nonEmpty(formData.get('model')) : null,
    dimensions:
      applianceType === 'hvac_filter' ? nonEmpty(formData.get('dimensions')) : null,
    last_service_date: lastService,
    next_service_due: nextServiceDue,
    service_interval_months: intervalMonths,
    spring_startup_date:
      applianceType === 'sprinkler'
        ? nonEmpty(formData.get('spring_startup_date'))
        : null,
    winterize_date:
      applianceType === 'sprinkler' ? nonEmpty(formData.get('winterize_date')) : null,
    notes: nonEmpty(formData.get('notes')),
  };

  if (!payload.name) throw new Error('Name is required');

  if (applianceId) {
    const { error } = await supabase
      .from('appliances')
      .update(payload)
      .eq('id', applianceId);
    if (error) throw error;
  } else {
    const { error } = await supabase.from('appliances').insert(payload);
    if (error) throw error;
  }

  revalidatePath(`/landlord/properties/${propertyId}`);
  redirect(`/landlord/properties/${propertyId}`);
}

export async function deleteAppliance(propertyId: string, applianceId: string) {
  const supabase = createClient();
  await supabase.from('appliances').delete().eq('id', applianceId);
  revalidatePath(`/landlord/properties/${propertyId}`);
  redirect(`/landlord/properties/${propertyId}`);
}

export async function markApplianceServiced(propertyId: string, applianceId: string) {
  const supabase = createClient();
  const { data: appl } = await supabase
    .from('appliances')
    .select('service_interval_months')
    .eq('id', applianceId)
    .maybeSingle();

  const today = format(new Date(), 'yyyy-MM-dd');
  const updates: { last_service_date: string; next_service_due: string | null } = {
    last_service_date: today,
    next_service_due: null,
  };
  if (appl?.service_interval_months) {
    updates.next_service_due = format(
      addMonths(parseISO(today), appl.service_interval_months),
      'yyyy-MM-dd',
    );
  }

  // Clear any open appliance reminders for this appliance — they'll be
  // regenerated by the next cron run if a new service is approaching.
  await supabase
    .from('reminders')
    .delete()
    .eq('appliance_id', applianceId)
    .eq('dismissed', false);

  const { error } = await supabase
    .from('appliances')
    .update(updates)
    .eq('id', applianceId);
  if (error) throw error;

  revalidatePath(`/landlord/properties/${propertyId}`);
  revalidatePath(`/landlord/properties/${propertyId}/appliances/${applianceId}`);
  revalidatePath('/landlord/reminders');
}
