-- Per-appliance recurring service schedules.

alter table public.appliances
  add column if not exists service_interval_months smallint
    check (service_interval_months is null or service_interval_months between 1 and 120);

-- Reminders generated for a specific appliance get an FK so the cron can
-- dedupe per-appliance instead of per-property.
alter table public.reminders
  add column if not exists appliance_id uuid
    references public.appliances(id) on delete cascade;

create index if not exists reminders_appliance_idx
  on public.reminders(appliance_id) where appliance_id is not null;

-- Replace the old name-pattern-matched hvac_annual / smoke_co_battery
-- reminders with the new per-appliance generator. Any rows that exist will
-- be regenerated by the next cron run.
delete from public.reminders where type in ('hvac_annual', 'smoke_co_battery');
